# Site settings
title: Alex Petropavlovsky
email: alex.petropavlovsky@smartcloud.io
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://petalvlad.github.io" # the base hostname & protocol for your site
github_username : petalvlad
twitter_username : petropavlovsky

# Build settings
markdown: kramdown
gems:
    - jekyll-redirect-from
